# llm.py
#
# This module handles communication with LLM APIs to generate commit messages.
# It uses the 'litellm' library to provide a unified interface for different
# LLM providers (OpenAI, Anthropic, etc.) and handles response parsing.

import json
import os
import re
import litellm
from dotenv import load_dotenv
from gitai.utils.exceptions import (
    LLMError, APIAuthenticationError, NetworkError, 
    RateLimitError, ConfigurationError
)
from gitai.utils.log import get_logger
from .prompt import build_system_prompt, build_user_prompt

logger = get_logger(__name__)

# ============================================================
# INITIALIZATION
# Configure LLM settings and load environment variables
# ============================================================

# Disable verbose logging to prevent sensitive data leakage
# litellm.set_verbose = False  # Commented out - litellm defaults to False

# Load API keys and configuration from .env file
load_dotenv()

# Build the system prompt once at module load time
# This defines the AI's behavior and output format expectations
SYSTEM_PROMPT = build_system_prompt()


# ============================================================
# HELPER FUNCTIONS
# ============================================================

def _extract_json(text: str) -> dict:
    """
    Extract and parse JSON from LLM response text.
    
    LLM responses often include markdown formatting (code fences) around
    JSON output. This function strips those markers and parses the content.
    
    Args:
        text (str): Raw text response from the LLM, potentially containing
            markdown code fences like ```json ... ```
    
    Returns:
        dict: Parsed JSON content as a Python dictionary
    
    Raises:
        json.JSONDecodeError: If the cleaned text is not valid JSON
        ValueError: If the text cannot be parsed after cleanup
    
    Example:
        >>> response = '```json\\n{"message": "fix: bug"}\\n```'
        >>> _extract_json(response)
        {'message': 'fix: bug'}
    """
    # Remove markdown code fences (``` or ```json) and strip whitespace
    text = re.sub(r"```(?:json)?", "", text).strip().strip("`").strip()
    return json.loads(text)


# ============================================================
# MAIN LLM FUNCTION
# Generates commit messages by calling LLM APIs
# ============================================================

def get_llm_report(schema: dict, config: dict) -> dict:
    """
    Generate a commit message by sending schema data to an LLM.
    
    This function takes structured change data (schema) and user preferences
    (config), constructs appropriate prompts, and calls the LLM API via litellm.
    It handles response parsing and provides fallback behavior for non-JSON
    responses.
    
    Args:
        schema (dict): Structured schema containing file changes and summaries.
            Typically generated by schema_builder module. Should include:
            - File-level change details
            - Line-by-line additions/deletions
            - Semantic summaries of changes
        config (dict): User configuration options including:
            - style: Commit message style preference (e.g., 'conventional')
            - length: Desired message length ('short', 'medium', 'long')
            - Other formatting preferences
    
    Returns:
        dict: Parsed LLM response containing:
            - message (str): The generated commit message
            - raw (str): Raw response text (included if JSON parsing fails)
            - Additional fields if LLM returns structured JSON
    
    Raises:
        ValueError: If LLM_MODEL environment variable is not set
        RuntimeError: If the LLM API call fails (network issues, auth errors, etc.)
    
    Example:
        >>> schema = {"files": [...], "summary": "Updated authentication"}
        >>> config = {"style": "conventional", "length": "short"}
        >>> report = get_llm_report(schema, config)
        >>> print(report["message"])
        "feat: enhance authentication flow"
    """
    # Get LLM configuration from environment variables
    model = os.getenv("LLM_MODEL")
    api_key = os.getenv("AI_KEY")

    # Validate that required configuration is present
    if not model:
        raise ConfigurationError(
            "LLM_MODEL environment variable is not set",
            details={"received_model": model},
            suggestion="Set LLM_MODEL in your .env file. Example: LLM_MODEL=gemini/gemini-2.5-flash"
        )
    
    if not api_key:
        logger.warning("AI_KEY is not set. API calls may fail if the model requires authentication.")

    # Build the user prompt with schema data and user preferences
    # This creates a contextualized request for the LLM
    user_prompt = build_user_prompt(schema, config)

    # Prepare API call parameters
    # Using litellm allows switching between different LLM providers seamlessly
    kwargs = {
        "model": model,
        "api_key": api_key,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt},
        ],
        "temperature": 0.2,  # Low temperature for more deterministic output
        "max_tokens": 1024,  # Allow enough tokens for full commit messages with body
    }

    # Execute the LLM API call with error handling
    try:
        logger.debug(f"Calling LLM API with model: {model}")
        response = litellm.completion(**kwargs)
    except litellm.AuthenticationError as e:
        raise APIAuthenticationError(
            "LLM API authentication failed",
            details={"model": model, "error": str(e)},
            suggestion="Verify your API key is correct and hasn't expired."
        )
    except litellm.RateLimitError as e:
        raise RateLimitError(
            "LLM API rate limit exceeded",
            details={"model": model, "error": str(e)},
            suggestion="Wait a moment before retrying, or consider upgrading your API plan."
        )
    except litellm.APIConnectionError as e:
        raise NetworkError(
            "Failed to connect to LLM API",
            details={"model": model, "error": str(e)},
            suggestion="Check your internet connection and try again."
        )
    except litellm.APIError as e:
        raise LLMError(
            f"LLM API returned an error: {str(e)}",
            details={"model": model, "error_type": type(e).__name__},
            suggestion="Check your API configuration and try again."
        )
    except Exception as e:
        # Check if it's a network-related error
        error_str = str(e).lower()
        if any(keyword in error_str for keyword in ["connection", "network", "timeout", "socket"]):
            raise NetworkError(
                "Network error while calling LLM API",
                details={"model": model, "error": str(e)},
                suggestion="Check your internet connection."
            )
        raise LLMError(
            f"Unexpected error calling LLM API: {str(e)}",
            details={"model": model, "error_type": type(e).__name__}
        )

    # Extract the text content from the response
    raw = response.choices[0].message.content.strip()

    # Attempt to parse as JSON for structured output
    # Falls back to treating as plain text if parsing fails
    try:
        result = _extract_json(raw)
    except (json.JSONDecodeError, ValueError):
        # Fallback: treat as plain text commit message
        # This handles cases where LLM returns unformatted text
        result = {
            "message": raw,
            "raw": raw
        }

    return result